### ISSUE TITLE
Can we comply with nlohmann include hierarchy in order to be flexible with external json?

### ISSUE THREAD

**Issue by sasmaster** [olrea/openai-cpp#10]
Hi.
I am using this library with my own  include of nlohmann json. That lib keeps header under 'include/nlohmann". In your library header json dependency looks like this:

`#include "json.hpp"  // nlohmann/json`

Can it be modified to: 

`#include "nlohmann/json.hpp"  // nlohmann/json`  ?

So that the users would not have to move json.hpp out from  nlohmann directory which is default in that library? 

Thanks.

**Comment by coin-au-carre** [comment]
Good point thanks I will definitely manage that :)
Meanwhile you can modify it yourself
