### ISSUE TITLE
Upload pictures

### ISSUE THREAD

**Issue by vrl8888** [olrea/openai-cpp#12]
Hello, how to upload a picture, can you give an example

**Comment by coin-au-carre** [comment]
Hello I am not sure what you are looking for do you want to:
- Create an image https://platform.openai.com/docs/api-reference/images ? see example [here](https://github.com/olrea/openai-cpp/blob/main/examples/04-image.cpp)
- Upload a file https://platform.openai.com/docs/api-reference/files/upload but here only fine tuning is available

**Comment by vrl8888** [comment]
> Hello I am not sure what you are looking for do you want to:
> 
> * Create an image https://platform.openai.com/docs/api-reference/images ? see example [here](https://github.com/olrea/openai-cpp/blob/main/examples/04-image.cpp)
> * Upload a file https://platform.openai.com/docs/api-reference/files/upload but here only fine tuning is available

penai::image().variation example？

**Comment by coin-au-carre** [comment]
I will work on this thanks

**Comment by coin-au-carre** [comment]
Added the features and examples @vrl8888 sorry for the delay it was indeed not working... You will have to pull master  or take the release [v0.1.3](https://github.com/olrea/openai-cpp/releases/tag/v0.1.3)
