### ISSUE TITLE
"SSL connect error" appearing only sometimes

### ISSUE THREAD

**Issue by Sokkero** [olrea/openai-cpp#2]
Hello, 
when using `openai::completion().create()` I sometimes get "SSL connect error". This seems to be happening infrequently and seemingly randomly. Is this a problem that is happening because of heavy load of openAI or is this something I can fix/work around? I am relatively new to using c++ so I apologise in advance if this question is irrelevant to this project or if there is an obvious fix.

**Comment by coin-au-carre** [comment]
Thank you for your report, I do not know could you provide some code and results in order to try to reproduce your problem ?

**Comment by Sokkero** [comment]
I used the example code of [examples/00-showcase.cpp](https://github.com/olrea/openai-cpp/blob/main/examples/00-showcase.cpp). I now have altered it a bit to retry with a delay of 500ms when this SSL error appears for a maximum of 10 times. Seems to be working this way

**Comment by coin-au-carre** [comment]
Could you copy paste the exact error if it happens again ? I will try to investigate this.

**Comment by coin-au-carre** [comment]
@Sokkernr1 this PR should solve this issue https://github.com/olrea/openai-cpp/pull/15. 
If you try from master branch we should not have this problem anymore.  I will close this issue feel free to reopen it (or create another one) if needed.
