### ISSUE TITLE
is the multipart/form-data return text like stream ?

### ISSUE THREAD

**Issue by xkungxfu** [olrea/openai-cpp#20]
Does anyone use this repo? Has it implemented the effect of returning messages letter by letter like stream? Or returning sentence by sentence is also fine.

**Comment by hivenet-floriandang** [comment]
Stream is not yet implemented see https://github.com/olrea/openai-cpp/issues/19 but it will be.
Yes some people use it.

**Comment by coin-au-carre** [comment]
The stream has to be implemented see https://github.com/olrea/openai-cpp/issues/19. You can use this library for every else without stream though if anything is missing we will add it.
