### ISSUE TITLE
Add the Speech-to-text API

### ISSUE THREAD

**Issue by aparatext** [olrea/openai-cpp#5]
OpenAI have recently added a new endpoint for their hosted Whisper API. For anyone interested in implementing it, the API reference is attached below.

## References

- https://platform.openai.com/docs/guides/speech-to-text/speech-to-text-beta
- https://platform.openai.com/docs/api-reference/audio
- https://openai.com/blog/introducing-chatgpt-and-whisper-apis

**Comment by hivenet-floriandang** [comment]
Thanks for letting me know. I will add those asap.

**Comment by coin-au-carre** [comment]
Thanks for letting me know. If anyone willing to implement this you are welcome.

**Comment by coin-au-carre** [comment]
Thanks to the work of @U-K-L  chat completions example has been added  https://github.com/olrea/openai-cpp/pull/3
Note that the API is still in beta so things might change.

**Comment by coin-au-carre** [comment]
I am currently working on adding audio WIP :)

EDIT: Implemented

**Comment by coin-au-carre** [comment]
@walking-octopus audio is implemented it works fine for me, feel free to ask questions if needed in another issue

**Comment by aparatext** [comment]
Thanks!
