### ISSUE TITLE
Compatible on macOS?

### ISSUE THREAD

**Issue by ghost** [olrea/openai-cpp#6]
Hello,

I am attempting to get this project working on my end. Unfortunately, I am running into issues. I believe the issue is that libcurl is not working properly on my end. Do you know where I can find a macOS compatible install for libcurl? The errors I am getting state that there are "Undefined symbols for architecture arm64"

**Comment by coin-au-carre** [comment]
Hello this should be straightforward since it is available with brew: https://everything.curl.dev/get/macos.

> When you install curl the tool with homebrew as described above, it also installs libcurl together with its associated headers.

**Comment by coin-au-carre** [comment]
@nadjarman I will close this issue feel free to reopen it if needed.
